### ISSUE TITLE
Win32API only supported on win32 at ..../modules/cygwin/manifests/install.pp

### ISSUE THREAD

**Issue by uherbst** [madelaney/puppet-cygwin#1]
Installed versions:
- Windows 2012 R2
- current (current at 2016/02/07) puppet agent on this windows server
- current (current at 2016/02/07) madelaney-cygwin module

puppet manifest includes just:
node 'd001dadw' {
  include '::cygwin'
}

Error on agent:
Error while evaluating a Function Call, Could not autoload puppet/parser/functions/in_path: WIin32API only supported on win32 at /etc/puppetlabs/code/environment/development/modules/cygwin/manifests/install.pp:645:7 on node d001dadw

**Comment by decibelhertz** [comment]
Same issue on a freshly installed Win 7 box running PE agent 2016.5.1.  I too am just doing `include ::cygwin`.  Puppetfile looks like:
```
$ grep cygwin Puppetfile 
mod 'mdelaney-cygwin',          '0.0.6'
```
Here is the agent run:
```
Running Puppet agent on demand ...
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/in_path: Win32API only supported on win32 at /etc/puppetlabs/code/environments/production/modules/cygwin/manifests/install.pp:64:7 on node <my windows node>
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
I am able to load the lib in Ruby and execute...
```
ruby 2.1.9p490 (2016-03-30 revision 54437) [x64-mingw32]

C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Puppet>irb
irb(main):001:0> require 'win32/registry'
=> true
irb(main):002:0> reg_type = Win32::Registry::KEY_READ | 0x100
=> 131353
```

Relevant facts... 
```
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Puppet>facter -p os
{
  architecture => "x64",
  family => "windows",
  hardware => "x86_64",
  name => "windows",
  release => {
    full => "7",
    major => "7"
  },
  windows => {
    system32 => "C:\Windows\system32"
  }
}
```
```
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Puppet>facter -p path
C:\Program Files\Puppet Labs\Puppet\puppet\bin;C:\Program Files\Puppet Labs\Pupp
et\facter\bin;C:\Program Files\Puppet Labs\Puppet\hiera\bin;C:\Program Files\Pup
pet Labs\Puppet\mcollective\bin;C:\Program Files\Puppet Labs\Puppet\bin;C:\Progr
am Files\Puppet Labs\Puppet\sys\ruby\bin;C:\Program Files\Puppet Labs\Puppet\sys
\tools\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Sy
stem32\WindowsPowerShell\v1.0\;C:\Program Files\Puppet Labs\Puppet\bin
```

**Comment by cxadmin** [comment]
I am getting error on fresh installed Windows-7 64-bit
```

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Serve
r Error: Evaluation Error: Error while evaluating a Function Call, Could not aut
oload puppet/parser/functions/in_path: Win32API only supported on win32 at /etc/
puppetlabs/code/environments/production/modules/cygwin/manifests/install.pp:64:7
 on node w7-env04.dm.cx
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

```

aio_agent_version => 1.8.3
ruby => {
  platform => "i386-mingw32",
  sitedir => "C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/site_r
uby/2.1.0",
  version => "2.1.9"
}

**Comment by sdavid14** [comment]
I am encountering the same error using the puppet learning vm:

/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
2017-07-20 14:30:42,963 ERROR [qtp431217787-62] [puppetserver] Puppet Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/in_path: Win32API only supported on win32 at /etc/puppetlabs/code/environments/production/modules/cygwin/manifests/install.pp:64:7 on node abcd

Any updates ?

**Comment by danielparks** [comment]
I'm really not sure why #3 fixes the issue, so I'd appreciate somebody else giving it a try.

I've got a few more PRs incoming.

**Comment by madelaney** [comment]
Version `0.1.0` should fix this.
